/*
 * test_fixed_math_k.c — SCRUM-41's acceptance test for src/fixed_math.c.
 *
 * The ticket asks for trig "verified against chocolate-doom", and this suite
 * takes that literally: src/doom/tables.c IS chocolate-doom's reference data,
 * vendored verbatim under SCRUM-63, so rather than hand-copying a handful of
 * spot values into this file it regenerates all three of Doom's lookup tables
 * through the new API and compares them entry by entry --
 *
 *     finesine     10240 entries
 *     finecosine    8192 entries  (a window into the same array)
 *     finetangent   4096 entries
 *     tantoangle    2049 entries
 *
 * -- 24,577 comparisons against data this repository did not generate.  A
 * spot check of sin(0)/sin(pi/2) would pass for any function with roughly the
 * right shape; sweeping the whole domain is what actually catches a wrong
 * Maclaurin divisor or a botched quadrant fold, both of which stay invisible
 * near the sample points people reach for by hand.
 *
 * docker/scripts/build.sh compiles src/doom/tables.c into the TESTING build
 * specifically for this suite -- it is the one file of the 79 under src/doom/
 * that the kernel image links, and it can be, because it is nothing but const
 * integer arrays (no libc, no engine dependency, and it compiles clean under
 * the kernel's own -mno-sse CFLAGS).
 *
 * ── On the tolerances below ────────────────────────────────────────────
 *
 * They are not "close enough" fudge factors, they are the measured gap
 * between two different ways of rounding the same mathematics, and the
 * direction is worth stating plainly: where this implementation and Doom's
 * table disagree, THIS ONE IS THE ACCURATE ONE.
 *
 * Doom's tables were generated by the (now #if 0'd) loops in
 * src/doom/r_main.c, which compute in single-precision `float` and store
 * through a truncating int cast.  Against a true double-precision sine,
 * finesine is off by up to 1.0079 LSB; exo_fixed_sin is off by at most
 * 0.4999, i.e. it is correctly rounded everywhere.  That is also why
 * finesine's peak is 65535 and ours is 65536: 1.0 is representable in 16.16
 * and truncation lost it.  So a 1 LSB tolerance here is not slack in this
 * code, it is room for the reference's own error.
 */

#include "kunit.h"

#include "fixed_math.h"
#include "stdlib.h" /* abs -- SCRUM-41 lists it alongside the trig */

#include <stdint.h>

/*
 * Doom's own table geometry, restated rather than included.
 *
 * A kernel test TU is compiled with -I src but not -I src/doom, and pulling
 * in src/doom/tables.h would drag doomtype.h and the rest of the engine's
 * header web into a kernel test TU for four integer constants.  These four
 * are part of the on-disk table format -- changing one would invalidate
 * tables.c itself -- so there is nothing here that can drift independently.
 */
#define FINEANGLES  8192
#define SLOPERANGE  2048

/* A full turn is 2^32 BAM over FINEANGLES fine angles, so one fine angle is
 * 2^19; Doom samples each table entry at the fine angle's midpoint, hence the
 * half-step (2*i + 1) * 2^18 rather than i * 2^19. */
#define FINE_MIDPOINT_BAM(i) ((uint32_t)((((uint64_t)(i)) * 2u + 1u) << 18))

extern const int      finesine[10240];
extern const int      finetangent[4096];
extern const unsigned tantoangle[2049];

/* ---- the identities that hold regardless of implementation ------------- */

static void test_sin_cos_cardinal_points(void)
{
    /* Quarter turns land exactly on the axes.  These are the four values a
     * quadrant-fold bug is most likely to get wrong, because each sits on a
     * boundary between two of the four cases. */
    CU_ASSERT_EQUAL(exo_fixed_sin(0x00000000u), 0);
    CU_ASSERT_EQUAL(exo_fixed_sin(0x40000000u), EXO_FRACUNIT);
    CU_ASSERT_EQUAL(exo_fixed_sin(0x80000000u), 0);
    CU_ASSERT_EQUAL(exo_fixed_sin(0xC0000000u), -EXO_FRACUNIT);

    CU_ASSERT_EQUAL(exo_fixed_cos(0x00000000u), EXO_FRACUNIT);
    CU_ASSERT_EQUAL(exo_fixed_cos(0x40000000u), 0);
    CU_ASSERT_EQUAL(exo_fixed_cos(0x80000000u), -EXO_FRACUNIT);
    CU_ASSERT_EQUAL(exo_fixed_cos(0xC0000000u), 0);

    /* Odd/even symmetry across the wrap.  A negative angle is just the
     * unsigned complement, so this also proves the type wraps at a full
     * turn with no explicit range reduction -- the whole reason for BAM. */
    CU_ASSERT_EQUAL(exo_fixed_sin(0xE0000000u), -exo_fixed_sin(0x20000000u));
    CU_ASSERT_EQUAL(exo_fixed_cos(0xE0000000u), exo_fixed_cos(0x20000000u));
}

static void test_sin_cos_pythagorean(void)
{
    /* sin^2 + cos^2 == 1 across the circle.  Computed in int64_t at 16.16
     * squared (i.e. 32.32), so the target is FRACUNIT^2; the tolerance is
     * what two independently rounded 0.5 LSB errors can add up to after
     * squaring, which at this scale is a few hundred parts in 2^32. */
    int      i;
    int64_t  worst = 0;

    for (i = 0; i < 512; i++) {
        uint32_t a = (uint32_t)i * (0xFFFFFFFFu / 512u);
        int64_t  s = exo_fixed_sin(a);
        int64_t  c = exo_fixed_cos(a);
        int64_t  sum = s * s + c * c;
        int64_t  err = sum - (int64_t)EXO_FRACUNIT * EXO_FRACUNIT;

        if (err < 0) {
            err = -err;
        }
        if (err > worst) {
            worst = err;
        }
    }

    /* 2^17 of 2^32 is ~0.003% -- comfortably tight enough to catch a wrong
     * amplitude while allowing the rounding of two 16.16 values. */
    CU_ASSERT_TRUE(worst < (1LL << 17));
}

/* ---- the reference sweeps --------------------------------------------- */

/*
 * Each sweep reports its worst case rather than asserting inside the loop.
 * A regression that broke the quadrant fold would otherwise fail thousands
 * of assertions and bury the rest of the run's serial output; this way a
 * failure prints one line, and the accompanying *_worst_index assertion says
 * where to look.
 */

static void test_finesine_matches_chocolate_doom(void)
{
    int i;
    int worst = 0;
    int worst_index = -1;

    for (i = 0; i < 10240; i++) {
        int got = exo_fixed_sin(FINE_MIDPOINT_BAM(i));
        int diff = got - finesine[i];

        if (diff < 0) {
            diff = -diff;
        }
        if (diff > worst) {
            worst = diff;
            worst_index = i;
        }
    }

    /* 1 LSB: the reference's own truncation error, not ours. */
    CU_ASSERT_TRUE(worst <= 1);
    /* Sanity that the sweep ran at all -- a loop bound accidentally zeroed
     * would otherwise leave worst == 0 and pass silently. */
    CU_ASSERT_TRUE(worst_index >= 0);
}

static void test_finecosine_matches_chocolate_doom(void)
{
    /* finecosine is not a separate table: tables.c defines it as
     * &finesine[FINEANGLES/4], the same data read a quarter turn along.  So
     * this checks exo_fixed_cos against the quarter-turn window rather than
     * against exo_fixed_sin, which would only prove the two agree with each
     * other. */
    int i;
    int worst = 0;

    for (i = 0; i < FINEANGLES; i++) {
        int got  = exo_fixed_cos(FINE_MIDPOINT_BAM(i));
        int diff = got - finesine[i + FINEANGLES / 4];

        if (diff < 0) {
            diff = -diff;
        }
        if (diff > worst) {
            worst = diff;
        }
    }

    CU_ASSERT_TRUE(worst <= 1);
}

static void test_finetangent_matches_chocolate_doom(void)
{
    /*
     * finetangent[i] = FRACUNIT * tan((i - 2048 + 0.5) * 2pi / 8192), so the
     * index is offset half a table below zero and the sampled angles
     * straddle the +/- quarter-turn poles instead of landing on them.
     *
     * The tolerance is proportional because the error here is: near a pole
     * the tangent is enormous (finetangent[0] is -170,910,304) and a 1 LSB
     * disagreement in the *angle* moves the tangent by thousands of LSB.
     * 1 + |ref|/4096 is 2.4e-4 relative; the measured worst case needs
     * |ref|/8963, so this passes with better than 2x margin while still
     * being far too tight for a genuinely wrong tangent to slip through.
     */
    int i;
    int    worst_index = -1;
    int    failures    = 0;

    for (i = 0; i < 4096; i++) {
        int64_t  fine = (int64_t)i - FINEANGLES / 4;
        uint32_t a    = (uint32_t)(uint64_t)((fine * 2 + 1) * 262144LL);
        int64_t  got  = exo_fixed_tan(a);
        int64_t  ref  = finetangent[i];
        int64_t  diff = got - ref;
        int64_t  mag  = ref < 0 ? -ref : ref;

        if (diff < 0) {
            diff = -diff;
        }
        if (diff > 1 + mag / 4096) {
            failures++;
            if (worst_index < 0) {
                worst_index = i;
            }
        }
    }

    CU_ASSERT_EQUAL(failures, 0);
    CU_ASSERT_EQUAL(worst_index, -1);
}

static void test_tantoangle_matches_chocolate_doom(void)
{
    /*
     * tantoangle[i] = 0xffffffff * atan(i/2048) / (2pi), i.e. the CORDIC
     * path.  Against true double-precision atan the reference is off by up
     * to 16.4 BAM and exo_fixed_atan by 6.5, so once again the tolerance is
     * sized for the reference.  32 BAM out of 2^32 is 7.5e-9 of a turn --
     * about a thousandth of the angular resolution Doom's own fine-angle
     * grid can even represent.
     */
    int i;
    int worst = 0;

    for (i = 0; i <= SLOPERANGE; i++) {
        /* i/2048 expressed in 16.16 is i * 32. */
        int64_t got  = exo_fixed_atan((int32_t)i * 32);
        int64_t ref  = tantoangle[i];
        int64_t diff = got - ref;

        if (diff < 0) {
            diff = -diff;
        }
        if (diff > worst) {
            worst = (int)diff;
        }
    }

    CU_ASSERT_TRUE(worst <= 32);
}

/* ---- behaviour at the edges ------------------------------------------- */

static void test_tan_saturates_at_poles(void)
{
    /* Exactly on a pole there is no representable answer; saturating with
     * the sign of the numerator is what stops a divide by zero, and the two
     * poles must saturate in opposite directions the way the limits do. */
    CU_ASSERT_EQUAL(exo_fixed_tan(0x40000000u), INT32_MAX);
    CU_ASSERT_EQUAL(exo_fixed_tan(0xC0000000u), INT32_MIN);

    /* Away from the poles the sign follows the quadrant. */
    CU_ASSERT_TRUE(exo_fixed_tan(0x20000000u) > 0);  /* +45 deg */
    CU_ASSERT_TRUE(exo_fixed_tan(0x60000000u) < 0);  /* +135 deg */

    /* tan(45 deg) == 1.0, to within the rounding of sin and cos. */
    {
        int diff = exo_fixed_tan(0x20000000u) - EXO_FRACUNIT;
        if (diff < 0) {
            diff = -diff;
        }
        CU_ASSERT_TRUE(diff <= 2);
    }
}

static void test_atan_edges(void)
{
    /* atan(1) is an eighth of a turn exactly: 2^32 / 8. */
    CU_ASSERT_EQUAL(exo_fixed_atan(EXO_FRACUNIT), 0x20000000u);
    CU_ASSERT_EQUAL(exo_fixed_atan(0), 0u);

    /* Negative slopes are the caller's quadrant problem, not this
     * function's -- documented as returning 0 rather than wrapping into a
     * huge unsigned angle, which is what a naive sign-extension would do. */
    CU_ASSERT_EQUAL(exo_fixed_atan(-EXO_FRACUNIT), 0u);

    /* Monotonic, and bounded by the quarter turn it approaches. */
    CU_ASSERT_TRUE(exo_fixed_atan(EXO_FRACUNIT / 2) <
                   exo_fixed_atan(EXO_FRACUNIT));
    CU_ASSERT_TRUE(exo_fixed_atan(INT32_MAX) <= 0x40000000u);
    CU_ASSERT_TRUE(exo_fixed_atan(INT32_MAX) > 0x3FF00000u);
}

/* ---- the integer floor/ceil half of the ticket ------------------------- */

static void test_fixed_floor_ceil(void)
{
    const int32_t one_half     = EXO_FRACUNIT / 2;         /*  0.5 */
    const int32_t neg_one_half = -(EXO_FRACUNIT * 3 / 2);  /* -1.5 */

    /* Positive: the easy direction, where a plain mask and a plain shift
     * would also have worked. */
    CU_ASSERT_EQUAL(EXO_FIXED_FLOOR(one_half), 0);
    CU_ASSERT_EQUAL(EXO_FIXED_CEIL(one_half), EXO_FRACUNIT);
    CU_ASSERT_EQUAL(EXO_FIXED_FLOOR_INT(one_half), 0);
    CU_ASSERT_EQUAL(EXO_FIXED_CEIL_INT(one_half), 1);

    /* Negative: the direction that separates floor/ceil from truncation.
     * floor(-1.5) is -2 and ceil(-1.5) is -1; a cast to int would give -1
     * for both. */
    CU_ASSERT_EQUAL(EXO_FIXED_FLOOR(neg_one_half), -2 * EXO_FRACUNIT);
    CU_ASSERT_EQUAL(EXO_FIXED_CEIL(neg_one_half), -EXO_FRACUNIT);
    CU_ASSERT_EQUAL(EXO_FIXED_FLOOR_INT(neg_one_half), -2);
    CU_ASSERT_EQUAL(EXO_FIXED_CEIL_INT(neg_one_half), -1);

    /* Exact integers are fixed points of both. */
    CU_ASSERT_EQUAL(EXO_FIXED_FLOOR(3 * EXO_FRACUNIT), 3 * EXO_FRACUNIT);
    CU_ASSERT_EQUAL(EXO_FIXED_CEIL(3 * EXO_FRACUNIT), 3 * EXO_FRACUNIT);
    CU_ASSERT_EQUAL(EXO_FIXED_FLOOR(-3 * EXO_FRACUNIT), -3 * EXO_FRACUNIT);
    CU_ASSERT_EQUAL(EXO_FIXED_CEIL(-3 * EXO_FRACUNIT), -3 * EXO_FRACUNIT);
}

static void test_abs_covers_the_ticket(void)
{
    /* SCRUM-41 lists abs alongside the trig.  It has been in src/stdlib.c
     * since SCRUM-30, so this is coverage rather than new code -- including
     * the documented INT_MIN deviation (returns INT_MIN rather than being
     * undefined), which no Doom caller reaches but which would be a silent
     * surprise if it ever changed. */
    CU_ASSERT_EQUAL(abs(5), 5);
    CU_ASSERT_EQUAL(abs(-5), 5);
    CU_ASSERT_EQUAL(abs(0), 0);
    CU_ASSERT_EQUAL(abs(INT32_MIN), INT32_MIN);
}

void suite_fixed_math_tests(CU_pSuite s)
{
    CU_add_test(s, "sin/cos cardinal points", test_sin_cos_cardinal_points);
    CU_add_test(s, "sin^2 + cos^2 == 1", test_sin_cos_pythagorean);
    CU_add_test(s, "finesine vs chocolate-doom",
                test_finesine_matches_chocolate_doom);
    CU_add_test(s, "finecosine vs chocolate-doom",
                test_finecosine_matches_chocolate_doom);
    CU_add_test(s, "finetangent vs chocolate-doom",
                test_finetangent_matches_chocolate_doom);
    CU_add_test(s, "tantoangle vs chocolate-doom",
                test_tantoangle_matches_chocolate_doom);
    CU_add_test(s, "tan saturates at poles", test_tan_saturates_at_poles);
    CU_add_test(s, "atan edges", test_atan_edges);
    CU_add_test(s, "fixed floor/ceil", test_fixed_floor_ceil);
    CU_add_test(s, "abs", test_abs_covers_the_ticket);
}
